name: MultiWorldMoney
main: com.wasteofplastic.multiworldmoney.MultiWorldMoney
version: ${version}
depend: [Vault]
softdepend: [Multiverse-Core]
commands:
   pay:
      description: Pays another player from your balance in this world to their balance in this world
      usage: /<command> [player] [amount]
      permission: mwm.pay
      permission-message: You don't have <permission>
   balance:
      description: This tells you how much money you have across all worlds.
      usage: /<command> [player]
      permission: mwm.balance
      permission-message: You don't have <permission>
   mwm:
      description: Admin command
      usage: /<command> to see help
permissions:
   mwm.balance:
      description: Gives access to the balance command
      default: true
   mwm.pay:
      description: Allows players to pay each other in-world
      default: true
   mwm.playerbalance:
      description: Enables checking of other player’s balances
      default: op
   mwm.admin:
      description: Access to admin commands
      default: op